# Backups
backups:
    - mysql:
        name: mydb
        user: mydb
        pass: mydb
        host: localhost
        port: 3306
        exclude:
          - mytable
        destinations:
          - local:
              frequency: '@always'
              retention: 14
              folder: '/mydb'